---
kind: Service
apiVersion: v1
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    application: sso
    component: server
metadata:
  name: sso
  labels:
    application: sso
    component: server
  annotations:
    description: The web server's http port.